version: "3.7"
services:
  mongodb:
    container_name: db
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - rushing-network
  mongo-seed:
    container_name: db-seed
    build: db/mongo/mongo-seed
    networks:
      - rushing-network
    depends_on:
      - mongodb
  api:
    container_name: api-server
    build: server
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongodb:27017
    ports:
      - 3000:3000
    networks:
      - rushing-network
    depends_on:
      - mongodb
  client:
    container_name: client-server
    build: client
    environment:
      - PORT=3100
      - API_URL=http://host.docker.internal:3000
    ports:
      - 3100:3100
    networks:
      - rushing-network
    depends_on:
      - api
networks:
  rushing-network:
