version: "3.7"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db

  mongo-seed:
    build: ./mongo/mongo-seed
    links:
      - mongodb
